# Generated by Django 5.0.4 on 2024-04-09 18:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('receiver', '0001_initial'),
        ('telegram', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Gate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='telegram.chat')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiver.group')),
            ],
            options={
                'unique_together': {('group', 'chat')},
            },
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('content', models.TextField()),
                ('is_blocked', models.BooleanField(default=False)),
                ('gate', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gateway.gate')),
                ('message', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='receiver.message')),
            ],
            options={
                'default_permissions': ['view'],
            },
        ),
        migrations.CreateModel(
            name='Rule',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('contain', 'Contain'), ('regex', 'Regex'), ('mask', 'Mask')], max_length=10)),
                ('name', models.CharField(max_length=256)),
                ('pattern', models.TextField()),
                ('is_active', models.BooleanField(default=True)),
                ('gate', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='gateway.gate')),
            ],
        ),
    ]
